/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package chat;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorCode implements org.apache.thrift.TEnum {
  usernameExists(1),
  signupError(2),
  loginError(3),
  invalidSession(4),
  invalidUserId(5),
  invalidCertificate(6),
  unknownError(7),
  sendMessageError(8),
  messageEmpty(9),
  usernameEmpty(10),
  passwordEmpty(11),
  messageTooLong(12);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 1:
        return usernameExists;
      case 2:
        return signupError;
      case 3:
        return loginError;
      case 4:
        return invalidSession;
      case 5:
        return invalidUserId;
      case 6:
        return invalidCertificate;
      case 7:
        return unknownError;
      case 8:
        return sendMessageError;
      case 9:
        return messageEmpty;
      case 10:
        return usernameEmpty;
      case 11:
        return passwordEmpty;
      case 12:
        return messageTooLong;
      default:
        return null;
    }
  }
}
